### PR TITLE
add catch and follow function

### PR DESCRIPTION
**Pull request by LANZ1KING**

### CODE REVIEW

**Comment by NagiicivA** [comment]
thanks

**Comment by NagiicivA** [comment]
thanks for your help，im appreciate to your contribution

**Comment by HuanCC666** [comment]
What a nice contribution! It fulfilled my needs. If possible, it would be better to add more comments to your code.

**Comment by undingable123** [comment]
Great! I like your publisher dictionary part, it's very inspiring.

**Pull request merged**
